; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = generic_esp32
;default_envs = esp12e
extra_configs = platformio_override.ini

[env]
; Make sure to NOT add any spaces in the custom_ci_action property
; (also the position in the file is important)
custom_ci_action = generic_esp32,esp12e

framework = arduino
platform = espressif32@6.10.0

board_build.partitions = partitions_custom_4mb.csv

build_flags =
    -DPIOENV=\"$PIOENV\"
    -D_TASK_STD_FUNCTION=1
    -D_TASK_THREAD_SAFE=1
    -Wall -Wextra -Wunused -Wmisleading-indentation -Wduplicated-cond -Wlogical-op -Wnull-dereference
;   Have to remove -Werror because of
;   https://github.com/espressif/arduino-esp32/issues/9044 and
;   https://github.com/espressif/arduino-esp32/issues/9045
;    -Werror
    -std=c++17
    -std=gnu++17
build_unflags =
    -std=gnu++11

lib_deps =
    arkhipenko/TaskScheduler @ 3.8.5
;    D:/GitHub/ESP32_PID/ESP32_PIDcontroller/src


[env:generic_esp32]
framework = arduino
platform = espressif32@6.5.0
board = esp32dev
build_flags = ${env.build_flags}

monitor_port = COM5
;debug_tool = esp-prog
;upload_protocol = esp-prog
;upload_speed = 921600

[env:esp12e]
platform = espressif8266
;platform = https://github.com/platformio/platform-espressif8266.git
framework = arduino
; framework = esp8266-rtos-sdk ; ### geht nicht!
board = esp12e
upload_port = COM13  ; ESP12F
